### ISSUE TITLE
Modify existing lv-client for Redux

### ISSUE THREAD

**Issue by Cheyans** [ripples/lecture-viewer#19]

**Comment by dylanfischler** [comment]
@Cheyans We should separate the UI into a src and dist directory (names can be changed). It makes more sense in terms of development organization, and I don't see a point in making the uncompiled files publicly available.

**Comment by dylanfischler** [comment]
@Cheyans I'd also like to move old files into a deprecated directory or something. If we keep them together, it's going to be harder in the future to go through and remove unused code.

**Comment by Cheyans** [comment]
Both sound good to me.

**Comment by Cheyans** [comment]
closed by ripples/lv-client#20
