### ISSUE TITLE
Sass Support

### ISSUE THREAD

**Issue by Cheyans** [ripples/lecture-viewer#38]
Sass in Webpack is handy for development, but has some drawbacks in Prod. 

**Firstly**: see [github/sass-loader#extracting-stylesheets](https://github.com/jtangelder/sass-loader#extracting-stylesheets)
**Secondly**: Webpack sass-loader doesn't support global imports, we're adding back this functionality with [sass-resource-loader](https://github.com/shakacode/sass-resources-loader), but this only supports single files (not libraries, or files with their own imports)

**Comment by dylanfischler** [comment]
Done
